[package]
name = "drawme"
version = "0.0.0"
edition = "2021"

[features]
serde = ["dep:serde", "nalgebra/serde-serialize", "url/serde"]

[dependencies]
fontdb = "0.23.0"
nalgebra = { version = "0.33", default-features = false, features = ["std"] }
#nalgebra = { version = "0.33", default-features = false }
serde = { version = "1.0", features = ["derive"], optional = true }
url = "2.5.4"
